"""Generated by scripts/generate-sdk.mjs from docs/openapi.json; do not edit."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any, Iterator
from urllib.parse import quote, urlencode


class QcgError(Exception):
    """Raised for non-2xx responses; carries the status and problem body."""

    def __init__(self, status: int, problem: Any, message: str) -> None:
        super().__init__(message)
        self.status = status
        self.problem = problem


class QcgClient:
    """Dependency-free client for the qcg HTTP API.

    The bearer token is sent only as an Authorization header. Event streams
    are read incrementally from the response body.
    """

    def __init__(self, base_url: str = "", token: str | None = None) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = token

    def set_token(self, token: str | None) -> None:
        self.token = token

    def _headers(self, extra: dict[str, str] | None = None) -> dict[str, str]:
        headers = dict(extra or {})
        if self.token:
            headers["authorization"] = f"Bearer {self.token}"
        return headers

    def _url(self, path: str, query: dict[str, Any] | None = None) -> str:
        if not query:
            return f"{self.base_url}{path}"
        cleaned = {key: value for key, value in query.items() if value is not None}
        return f"{self.base_url}{path}?{urlencode(cleaned)}"

    def _request(
        self,
        method: str,
        path: str,
        query: dict[str, Any] | None = None,
        body: Any = None,
        headers: dict[str, str] | None = None,
    ) -> Any:
        data = None if body is None else json.dumps(body).encode("utf-8")
        extra = dict(headers or {})
        if body is not None:
            extra["content-type"] = "application/json"
        request = urllib.request.Request(
            self._url(path, query), data=data, method=method, headers=self._headers(extra)
        )
        try:
            with urllib.request.urlopen(request) as response:
                payload = response.read()
                if response.status == 204 or not payload:
                    return None
                return json.loads(payload.decode("utf-8"))
        except urllib.error.HTTPError as error:
            raw = error.read().decode("utf-8", errors="replace")
            try:
                problem = json.loads(raw) if raw else {}
            except json.JSONDecodeError:
                problem = {"detail": raw}
            detail = problem.get("detail") if isinstance(problem, dict) else None
            raise QcgError(error.code, problem, detail or error.reason or str(error.code)) from error

    def stream_run_events(self, run_id: str, last_event_id: int | None = None) -> Iterator[Any]:
        """Yields parsed SSE event payloads until the stream ends."""
        headers = self._headers()
        if last_event_id is not None:
            headers["last-event-id"] = str(last_event_id)
        request = urllib.request.Request(
            self._url(f"/api/runs/{quote(str(run_id), safe='')}/events"), headers=headers
        )
        with urllib.request.urlopen(request) as response:
            buffer = ""
            while True:
                chunk = response.read(4096)
                if not chunk:
                    return
                buffer += chunk.decode("utf-8", errors="replace")
                while "\n\n" in buffer:
                    frame, buffer = buffer.split("\n\n", 1)
                    data = "".join(
                        line[5:].lstrip() for line in frame.split("\n") if line.startswith("data:")
                    )
                    if data:
                        yield json.loads(data)

    def list_generators(self):
        return self._request("GET", "/api/generators")

    def get_generator(self, id):
        return self._request("GET", f"/api/generators/{id}")

    def read_generator_asset(self, id, path):
        return self._request("GET", f"/api/generators/{id}/assets/{path}")

    def llm_catalog(self, query=None):
        return self._request("GET", "/api/llm/catalog", query=query)

    def complete_mcp_authorization(self, query=None):
        return self._request("GET", "/api/mcp/oauth/callback", query=query)

    def list_mcp_servers(self):
        return self._request("GET", "/api/mcp/servers")

    def start_mcp_authorization(self, id):
        return self._request("POST", f"/api/mcp/servers/{id}/authorization")

    def clear_mcp_authorization(self, id):
        return self._request("DELETE", f"/api/mcp/servers/{id}/authorization")

    def cancel_pending_mcp_authorization(self, id):
        return self._request("DELETE", f"/api/mcp/servers/{id}/authorization/pending")

    def openapi(self):
        return self._request("GET", "/api/openapi.json")

    def list_runs(self, query=None):
        return self._request("GET", "/api/runs", query=query)

    def start_run(self, body=None):
        return self._request("POST", "/api/runs", body=body)

    def get_run(self, id):
        return self._request("GET", f"/api/runs/{id}")

    def cancel_run_alias(self, id):
        return self._request("POST", f"/api/runs/{id}")

    def delete_run(self, id):
        return self._request("DELETE", f"/api/runs/{id}")

    def list_artifacts(self, id):
        return self._request("GET", f"/api/runs/{id}/artifacts")

    def download_artifacts_zip(self, id):
        return self._request("GET", f"/api/runs/{id}/artifacts.zip")

    def read_artifact(self, id, path):
        return self._request("GET", f"/api/runs/{id}/artifacts/{path}")

    def download_run_bundle(self, id):
        return self._request("GET", f"/api/runs/{id}/bundle")

    def confirm_run(self, id, cid, body=None):
        return self._request("PUT", f"/api/runs/{id}/confirmations/{cid}", body=body)

    def run_events(self, id):
        return self._request("GET", f"/api/runs/{id}/events")

    def fork_run(self, id, body=None):
        return self._request("POST", f"/api/runs/{id}/fork", body=body)

    def read_run_journal(self, id):
        return self._request("GET", f"/api/runs/{id}/journal")

    def read_run_metrics(self, id):
        return self._request("GET", f"/api/runs/{id}/metrics")

    def answer_question(self, id, qid, body=None):
        return self._request("PUT", f"/api/runs/{id}/questions/{qid}", body=body)

    def cancel_run(self, id):
        return self._request("POST", f"/api/runs/{id}:cancel")

    def health(self):
        return self._request("GET", "/healthz")

    def metrics(self):
        return self._request("GET", "/metrics")
