[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
camino.workspace = true
api = { path = "../../crates/api" }
contract = { path = "../../crates/contract" }
engine = { path = "../../crates/engine" }
files = { path = "../../crates/files" }
policy = { path = "../../crates/policy" }
server = { path = "../../crates/server" }
service = { path = "../../crates/service" }
model = { path = "../../crates/model" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
toml.workspace = true
