[package]
name = "qcg-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
camino.workspace = true
qcg-contract = { path = "../../crates/qcg-contract" }
qcg-engine = { path = "../../crates/qcg-engine" }
qcg-server = { path = "../../crates/qcg-server" }
qcg-service = { path = "../../crates/qcg-service" }
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
walkdir.workspace = true
tokio-util.workspace = true
toml.workspace = true
