// Generated by scripts/generate-sdk.mjs from docs/openapi.json; do not edit.
import type { paths } from "./types";

export type QcgClientOptions = {
  /** Origin for the API, for example `http://127.0.0.1:8080`. Defaults to same-origin. */
  baseUrl?: string;
  /** Bearer token for an authenticated instance; sent only as a header. */
  token?: string;
  /** Fetch implementation override (tests, Node runtimes). */
  fetch?: typeof fetch;
};

export class QcgError extends Error {
  constructor(
    public readonly status: number,
    public readonly problem: unknown,
    message: string,
  ) {
    super(message);
    this.name = "QcgError";
  }
}

export class QcgClient {
  private readonly baseUrl: string;
  private token?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: QcgClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? "").replace(/\/$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
  }

  /** Replaces the bearer token for subsequent requests. */
  setToken(token: string | undefined): void {
    this.token = token;
  }

  private url(path: string, query?: Record<string, unknown>): string {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value !== undefined && value !== null) params.set(key, String(value));
    }
    const suffix = params.size > 0 ? `?${params.toString()}` : "";
    return `${this.baseUrl}${path}${suffix}`;
  }

  private headers(extra?: Record<string, string>): Record<string, string> {
    return {
      ...(this.token ? { authorization: `Bearer ${this.token}` } : {}),
      ...extra,
    };
  }

  async request<T>(
    method: string,
    path: string,
    options: { query?: Record<string, unknown>; body?: unknown } = {},
  ): Promise<T> {
    const headers: Record<string, string> = this.headers(
      options.body === undefined ? undefined : { "content-type": "application/json" },
    );
    const response = await this.fetchImpl(this.url(path, options.query), {
      method,
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    if (!response.ok) {
      const problem = await readProblem(response);
      throw new QcgError(response.status, problem, problemMessage(problem) || response.statusText);
    }
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  }

  private async text(path: string): Promise<string> {
    const response = await this.fetchImpl(this.url(path), { headers: this.headers() });
    if (!response.ok) {
      const problem = await readProblem(response);
      throw new QcgError(response.status, problem, problemMessage(problem) || response.statusText);
    }
    return response.text();
  }

  /** Reads run events as server-sent event JSON payloads, resuming from an id. */
  async *streamRunEvents(runId: string, lastEventId?: number): AsyncGenerator<unknown> {
    const response = await this.fetchImpl(
      this.url(`/api/runs/${encodeURIComponent(runId)}/events`),
      {
        headers: this.headers(
          lastEventId === undefined ? undefined : { "last-event-id": String(lastEventId) },
        ),
      },
    );
    if (!response.ok || !response.body) {
      const problem = await readProblem(response);
      throw new QcgError(response.status, problem, problemMessage(problem) || response.statusText);
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) return;
      buffer += decoder.decode(value, { stream: true });
      let boundary = buffer.indexOf("\n\n");
      while (boundary >= 0) {
        const frame = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        const data = frame
          .split("\n")
          .filter((line) => line.startsWith("data:"))
          .map((line) => line.slice(5).trimStart())
          .join("");
        if (data) yield JSON.parse(data) as unknown;
        boundary = buffer.indexOf("\n\n");
      }
    }
  }

  async listGenerators(): Promise<paths["/api/generators"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/generators`);
  }

  async getGenerator(id: string): Promise<paths["/api/generators/{id}"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/generators/${encodeURIComponent(id)}`);
  }

  async readGeneratorAsset(id: string, path: string): Promise<void> {
    return this.request("GET", `/api/generators/${encodeURIComponent(id)}/assets/${encodeURIComponent(path)}`);
  }

  async llmCatalog(query?: paths["/api/llm/catalog"]["get"]["parameters"]["query"]): Promise<paths["/api/llm/catalog"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/llm/catalog`, { query });
  }

  async completeMcpAuthorization(query?: paths["/api/mcp/oauth/callback"]["get"]["parameters"]["query"]): Promise<void> {
    return this.request("GET", `/api/mcp/oauth/callback`, { query });
  }

  async listMcpServers(): Promise<paths["/api/mcp/servers"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/mcp/servers`);
  }

  async startMcpAuthorization(id: string): Promise<paths["/api/mcp/servers/{id}/authorization"]["post"]["responses"][200]["content"]["application/json"]> {
    return this.request("POST", `/api/mcp/servers/${encodeURIComponent(id)}/authorization`);
  }

  async clearMcpAuthorization(id: string): Promise<void> {
    return this.request("DELETE", `/api/mcp/servers/${encodeURIComponent(id)}/authorization`);
  }

  async cancelPendingMcpAuthorization(id: string): Promise<void> {
    return this.request("DELETE", `/api/mcp/servers/${encodeURIComponent(id)}/authorization/pending`);
  }

  async openapi(): Promise<paths["/api/openapi.json"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/openapi.json`);
  }

  async listRuns(query?: paths["/api/runs"]["get"]["parameters"]["query"]): Promise<paths["/api/runs"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/runs`, { query });
  }

  async startRun(body: paths["/api/runs"]["post"]["requestBody"]["content"]["application/json"]): Promise<paths["/api/runs"]["post"]["responses"][201]["content"]["application/json"]> {
    return this.request("POST", `/api/runs`, { body });
  }

  async getRun(id: string): Promise<paths["/api/runs/{id}"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}`);
  }

  async cancelRunAlias(id: string): Promise<paths["/api/runs/{id}"]["post"]["responses"][200]["content"]["application/json"]> {
    return this.request("POST", `/api/runs/${encodeURIComponent(id)}`);
  }

  async deleteRun(id: string): Promise<void> {
    return this.request("DELETE", `/api/runs/${encodeURIComponent(id)}`);
  }

  async listArtifacts(id: string): Promise<paths["/api/runs/{id}/artifacts"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/artifacts`);
  }

  async downloadArtifactsZip(id: string): Promise<void> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/artifacts.zip`);
  }

  async readArtifact(id: string, path: string): Promise<void> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/artifacts/${encodeURIComponent(path)}`);
  }

  async downloadRunBundle(id: string): Promise<void> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/bundle`);
  }

  async confirmRun(id: string, cid: string, body: paths["/api/runs/{id}/confirmations/{cid}"]["put"]["requestBody"]["content"]["application/json"]): Promise<paths["/api/runs/{id}/confirmations/{cid}"]["put"]["responses"][200]["content"]["application/json"]> {
    return this.request("PUT", `/api/runs/${encodeURIComponent(id)}/confirmations/${encodeURIComponent(cid)}`, { body });
  }

  async runEvents(id: string): Promise<void> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/events`);
  }

  async forkRun(id: string, body: paths["/api/runs/{id}/fork"]["post"]["requestBody"]["content"]["application/json"]): Promise<paths["/api/runs/{id}/fork"]["post"]["responses"][201]["content"]["application/json"]> {
    return this.request("POST", `/api/runs/${encodeURIComponent(id)}/fork`, { body });
  }

  async readRunJournal(id: string): Promise<void> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/journal`);
  }

  async readRunMetrics(id: string): Promise<paths["/api/runs/{id}/metrics"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/api/runs/${encodeURIComponent(id)}/metrics`);
  }

  async answerQuestion(id: string, qid: string, body: paths["/api/runs/{id}/questions/{qid}"]["put"]["requestBody"]["content"]["application/json"]): Promise<paths["/api/runs/{id}/questions/{qid}"]["put"]["responses"][200]["content"]["application/json"]> {
    return this.request("PUT", `/api/runs/${encodeURIComponent(id)}/questions/${encodeURIComponent(qid)}`, { body });
  }

  async cancelRun(id: string): Promise<paths["/api/runs/{id}:cancel"]["post"]["responses"][200]["content"]["application/json"]> {
    return this.request("POST", `/api/runs/${encodeURIComponent(id)}:cancel`);
  }

  async health(): Promise<paths["/healthz"]["get"]["responses"][200]["content"]["application/json"]> {
    return this.request("GET", `/healthz`);
  }

  async metrics(): Promise<void> {
    return this.request("GET", `/metrics`);
  }
}

async function readProblem(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) return {};
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return { detail: text };
  }
}

function problemMessage(problem: unknown): string {
  if (problem && typeof problem === "object" && "detail" in problem) {
    const detail = (problem as { detail?: unknown }).detail;
    if (typeof detail === "string") return detail;
  }
  return "";
}
