// Generated by scripts/generate-sdk.mjs from docs/openapi.json; do not edit.
import type { paths } from "./types";

export type QcgClientOptions = {
  /** Origin for the API, for example `http://127.0.0.1:8080`. Defaults to same-origin. */
  baseUrl?: string;
  /** Bearer token for an authenticated instance; sent only as a header. */
  token?: string;
  /** Fetch implementation override (tests, Node runtimes). */
  fetch?: typeof fetch;
};

export type RequestOptions = {
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
  idempotencyKey?: string;
};

export class QcgError extends Error {
  constructor(
    public readonly status: number,
    public readonly problem: unknown,
    message: string,
  ) {
    super(message);
    this.name = "QcgError";
  }
}

/** Encodes one path segment (no slashes survive). */
function encodeSegment(value: string): string {
  return encodeURIComponent(value);
}

/** Encodes a multi-segment wildcard path, preserving slashes. */
function encodePathParam(value: string): string {
  return value
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
}

export class QcgClient {
  private readonly baseUrl: string;
  private token?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: QcgClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? "").replace(/\/$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
  }

  /** Replaces the bearer token for subsequent requests. */
  setToken(token: string | undefined): void {
    this.token = token;
  }

  private url(path: string, query?: Record<string, unknown>): string {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) continue;
      if (typeof value === "boolean") params.set(key, value ? "true" : "false");
      else params.set(key, String(value));
    }
    const suffix = params.size > 0 ? `?${params.toString()}` : "";
    return `${this.baseUrl}${path}${suffix}`;
  }

  private headers(extra?: Record<string, string>): Record<string, string> {
    return {
      ...(this.token ? { authorization: `Bearer ${this.token}` } : {}),
      ...extra,
    };
  }

  private withIdempotency(
    extra?: Record<string, string>,
    idempotencyKey?: string,
  ): Record<string, string> | undefined {
    if (idempotencyKey === undefined) return extra;
    return { ...extra, "idempotency-key": idempotencyKey };
  }

  private static readonly MAX_REDIRECTS = 5;

  private async checkedFetch(
    url: string,
    init: RequestInit,
    hops = 0,
    visited: string[] = [],
  ): Promise<Response> {
    // G05: manual redirects are followed finitely (max 5 hops) with cycle
    // detection and a clear error. Unbounded recursion previously followed
    // self-loops forever; the hop count and the visited list bound it.
    // The bearer token lives only in memory and is stripped cross-origin
    // or over a TLS downgrade (F04, preserved).
    const response = await this.fetchImpl(url, { ...init, redirect: "manual" });
    const location = response.headers.get("location");
    if (
      location !== null &&
      [301, 302, 303, 307, 308].includes(response.status)
    ) {
      // The request URL may be relative (default same-origin "/api/..."),
      // which URL() cannot parse as a base: resolve it first so relative
      // Locations and origin comparisons work in every runtime (G05-02).
      let current: URL;
      let next: URL;
      try {
        current = new URL(url, this.absoluteBaseFor(url));
        next = new URL(location, current);
      } catch {
        await this.discardBody(response);
        throw new QcgError(
          response.status,
          {},
          "redirect location is not a valid URL: " + location,
        );
      }
      if (hops >= QcgClient.MAX_REDIRECTS) {
        await this.discardBody(response);
        throw new QcgError(
          response.status,
          {},
          "redirect limit exceeded after " + QcgClient.MAX_REDIRECTS + " hops",
        );
      }
      if (visited.includes(next.href)) {
        await this.discardBody(response);
        throw new QcgError(response.status, {}, "redirect cycle detected: " + next.href);
      }
      const crossOrigin = next.origin !== current.origin;
      const downgrade = current.protocol === "https:" && next.protocol !== "https:";
      const initHeaders = new Headers(init.headers);
      if ((crossOrigin || downgrade) && initHeaders.has("authorization")) {
        initHeaders.delete("authorization");
      }
      const nextInit: RequestInit = { ...init, headers: initHeaders };
      // 303 always becomes GET (except HEAD); 301/302 POST becomes GET.
      if (
        response.status === 303 ||
        ((response.status === 301 || response.status === 302) &&
          (init.method ?? "GET") === "POST")
      ) {
        nextInit.method = "GET";
        nextInit.body = undefined;
        initHeaders.delete("content-type");
        initHeaders.delete("content-length");
      }
      // G05-04: release the intermediate response before following, so an
      // abandoned redirect chain cannot accumulate unread connections.
      await this.discardBody(response);
      return this.checkedFetch(next.href, nextInit, hops + 1, [...visited, current.href]);
    }
    return response;
  }

  private absoluteBaseFor(url: string): string | undefined {
    // Absolute request URLs need no base. Otherwise prefer the configured
    // baseUrl when it is absolute; in browsers fall back to the document
    // base so same-origin "/api/..." resolves; in Node without a base,
    // use a dummy origin purely for resolution (the fetch itself already
    // received the original url).
    try {
      new URL(url);
      return undefined;
    } catch {
      // Relative: fall through to the base candidates below.
    }
    if (this.baseUrl) {
      try {
        new URL(this.baseUrl);
        return this.baseUrl;
      } catch {
        // Non-absolute baseUrl: try the runtime location next.
      }
    }
    try {
      const href = (globalThis as { location?: { href?: unknown } }).location?.href;
      if (typeof href === "string" && href) return href;
    } catch {
      // No location: use the dummy origin below.
    }
    return "http://localhost";
  }

  private async discardBody(response: Response): Promise<void> {
    try {
      if (response.body) await response.body.cancel();
    } catch {
      // Best-effort: the connection may already be closed.
    }
  }

  private async readProblem(response: Response): Promise<unknown> {
    const text = await response.text();
    if (!text) return {};
    try {
      return JSON.parse(text) as unknown;
    } catch {
      return { detail: text };
    }
  }

  private async throwForStatus(response: Response): Promise<never> {
    const problem = await this.readProblem(response);
    throw new QcgError(response.status, problem, problemMessage(problem) || response.statusText);
  }

  async request<T>(
    method: string,
    path: string,
    options: { query?: Record<string, unknown>; body?: unknown } = {},
  ): Promise<T> {
    return this.requestJson(method, path, options);
  }

  private async requestJson<T>(
    method: string,
    path: string,
    options: RequestOptions = {},
  ): Promise<T> {
    const headers = this.headers(
      options.body === undefined ? options.headers : { "content-type": "application/json", ...options.headers },
    );
    const response = await this.checkedFetch(this.url(path, options.query), {
      method,
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    if (response.status === 304) return null as T;
    if (!response.ok) await this.throwForStatus(response);
    if (response.status === 204) return undefined as T;
    const text = await response.text();
    if (!text) return undefined as T;
    return JSON.parse(text) as T;
  }

  private async requestText(
    method: string,
    path: string,
    options: RequestOptions = {},
  ): Promise<string | null> {
    const response = await this.checkedFetch(this.url(path, options.query), {
      method,
      headers: this.headers(options.headers),
    });
    if (response.status === 304) return null;
    if (!response.ok) await this.throwForStatus(response);
    return response.text();
  }

  private async requestBytes(
    method: string,
    path: string,
    options: RequestOptions = {},
  ): Promise<Uint8Array | null> {
    const response = await this.checkedFetch(this.url(path, options.query), {
      method,
      headers: this.headers(options.headers),
    });
    if (response.status === 304) return null;
    if (!response.ok) await this.throwForStatus(response);
    return new Uint8Array(await response.arrayBuffer());
  }

  private async requestNdjson(
    method: string,
    path: string,
    options: RequestOptions = {},
  ): Promise<unknown[] | null> {
    const text = await this.requestText(method, path, options);
    if (text === null) return null;
    return text
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .map((line) => JSON.parse(line) as unknown);
  }

  private async requestEmpty(method: string, path: string, options: RequestOptions = {}): Promise<void> {
    const headers = this.headers(
      options.body === undefined ? options.headers : { "content-type": "application/json", ...options.headers },
    );
    const response = await this.checkedFetch(this.url(path, options.query), {
      method,
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    if (!response.ok) await this.throwForStatus(response);
  }

  private async text(path: string): Promise<string> {
    const result = await this.requestText("GET", path, {});
    if (result === null) return "";
    return result;
  }

  /** Reads run events as server-sent event JSON payloads, resuming from an id. */
  async *streamRunEvents(runId: string, lastEventId?: number): AsyncGenerator<unknown> {
    const response = await this.checkedFetch(
      this.url(`/api/runs/${encodeURIComponent(runId)}/events`),
      {
        headers: this.headers(
          lastEventId === undefined ? undefined : { "last-event-id": String(lastEventId) },
        ),
      },
    );
    if (!response.ok || !response.body) {
      await this.throwForStatus(response);
    }
    const reader = response.body!.getReader();
    try {
      const decoder = new TextDecoder();
      let buffer = "";
      let pendingCr = false;
      while (true) {
        const { done, value } = await reader.read();
        if (done) {
          // G04: EOF resolves a dangling CR, then dispatches frames already
          // terminated by a blank line and discards only the truly
          // unterminated tail (SSE spec). The decoder flush only completes
          // a split multibyte character, which can never create the ASCII
          // blank line that frames an event.
          try {
            decoder.decode();
          } catch {
            // Best-effort flush: a malformed tail is still discarded.
          }
          if (pendingCr) {
            buffer += "\n";
            pendingCr = false;
          }
          let tail = buffer.indexOf("\n\n");
          while (tail >= 0) {
            const frame = buffer.slice(0, tail);
            buffer = buffer.slice(tail + 2);
            const payload = parseSseFrame(frame);
            if (payload !== undefined) yield payload;
            tail = buffer.indexOf("\n\n");
          }
          return;
        }
        let piece = decoder.decode(value, { stream: true });
        // G04: a CRLF split across chunks frames as one break, never two.
        // A trailing CR is held until the next chunk proves LF pairing.
        if (pendingCr) {
          if (piece.startsWith("\n")) {
            buffer += "\n";
            piece = piece.slice(1);
          } else {
            buffer += "\n";
          }
          pendingCr = false;
        }
        if (piece.endsWith("\r")) {
          piece = piece.slice(0, -1);
          pendingCr = true;
        }
        if (piece) {
          piece = piece.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
          buffer += piece;
        }
        let boundary = buffer.indexOf("\n\n");
        while (boundary >= 0) {
          const frame = buffer.slice(0, boundary);
          buffer = buffer.slice(boundary + 2);
          const payload = parseSseFrame(frame);
          if (payload !== undefined) yield payload;
          boundary = buffer.indexOf("\n\n");
        }
      }
    } finally {
      try {
        await reader.cancel();
      } catch {
        // Cancel is best-effort: the connection may already be closed.
      }
      reader.releaseLock();
    }
  }

  async listGenerators(): Promise<paths["/api/generators"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/generators"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/generators`);
  }

  async getGenerator(id: string, options?: { headers?: Record<string, string> }): Promise<paths["/api/generators/{id}"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/generators/{id}"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/generators/${encodeURIComponent(id)}`, { headers: options?.headers });
  }

  async readGeneratorAsset(id: string, path: string): Promise<Uint8Array | null> {
    return this.requestBytes("GET", `/api/generators/${encodeURIComponent(id)}/assets/${encodePathParam(path)}`);
  }

  async llmCatalog(query?: paths["/api/llm/catalog"]["get"]["parameters"]["query"], options?: { query?: Record<string, unknown>; headers?: Record<string, string> }): Promise<paths["/api/llm/catalog"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/llm/catalog"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/llm/catalog`, { query, headers: options?.headers });
  }

  async completeMcpAuthorization(query?: paths["/api/mcp/oauth/callback"]["get"]["parameters"]["query"], options?: { query?: Record<string, unknown>; headers?: Record<string, string> }): Promise<string | null> {
    return this.requestText("GET", `/api/mcp/oauth/callback`, { query, headers: options?.headers });
  }

  async listMcpServers(): Promise<paths["/api/mcp/servers"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/mcp/servers"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/mcp/servers`);
  }

  async startMcpAuthorization(id: string): Promise<paths["/api/mcp/servers/{id}/authorization"]["post"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/mcp/servers/{id}/authorization"]["post"]["responses"][200]["content"]["application/json"] | null>("POST", `/api/mcp/servers/${encodeURIComponent(id)}/authorization`);
  }

  async clearMcpAuthorization(id: string): Promise<void> {
    return this.requestEmpty("DELETE", `/api/mcp/servers/${encodeURIComponent(id)}/authorization`);
  }

  async cancelPendingMcpAuthorization(id: string): Promise<void> {
    return this.requestEmpty("DELETE", `/api/mcp/servers/${encodeURIComponent(id)}/authorization/pending`);
  }

  async openapi(): Promise<paths["/api/openapi.json"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/openapi.json"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/openapi.json`);
  }

  async listRuns(query?: paths["/api/runs"]["get"]["parameters"]["query"], options?: { query?: Record<string, unknown>; headers?: Record<string, string> }): Promise<paths["/api/runs"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/runs`, { query, headers: options?.headers });
  }

  async startRun(body: paths["/api/runs"]["post"]["requestBody"]["content"]["application/json"], options?: { body?: unknown; headers?: Record<string, string>; idempotencyKey?: string }): Promise<paths["/api/runs"]["post"]["responses"][201]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs"]["post"]["responses"][201]["content"]["application/json"] | null>("POST", `/api/runs`, { body: body ?? options?.body, headers: this.withIdempotency(options?.headers, options?.idempotencyKey) });
  }

  async getRun(id: string, options?: { headers?: Record<string, string> }): Promise<paths["/api/runs/{id}"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/runs/${encodeURIComponent(id)}`, { headers: options?.headers });
  }

  async deleteRun(id: string): Promise<void> {
    return this.requestEmpty("DELETE", `/api/runs/${encodeURIComponent(id)}`);
  }

  async listArtifacts(id: string, options?: { headers?: Record<string, string> }): Promise<paths["/api/runs/{id}/artifacts"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}/artifacts"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/runs/${encodeURIComponent(id)}/artifacts`, { headers: options?.headers });
  }

  async downloadArtifactsZip(id: string): Promise<Uint8Array | null> {
    return this.requestBytes("GET", `/api/runs/${encodeURIComponent(id)}/artifacts.zip`);
  }

  async readArtifact(id: string, path: string): Promise<Uint8Array | null> {
    return this.requestBytes("GET", `/api/runs/${encodeURIComponent(id)}/artifacts/${encodePathParam(path)}`);
  }

  async downloadRunBundle(id: string): Promise<Uint8Array | null> {
    return this.requestBytes("GET", `/api/runs/${encodeURIComponent(id)}/bundle`);
  }

  async confirmRun(id: string, cid: string, body: paths["/api/runs/{id}/confirmations/{cid}"]["put"]["requestBody"]["content"]["application/json"], options?: { body?: unknown; headers?: Record<string, string>; idempotencyKey?: string }): Promise<paths["/api/runs/{id}/confirmations/{cid}"]["put"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}/confirmations/{cid}"]["put"]["responses"][200]["content"]["application/json"] | null>("PUT", `/api/runs/${encodeURIComponent(id)}/confirmations/${encodeURIComponent(cid)}`, { body: body ?? options?.body, headers: this.withIdempotency(options?.headers, options?.idempotencyKey) });
  }

  async runEvents(id: string, options?: { headers?: Record<string, string> }): Promise<string | null> {
    return this.requestText("GET", `/api/runs/${encodeURIComponent(id)}/events`, { headers: options?.headers });
  }

  async forkRun(id: string, body: paths["/api/runs/{id}/fork"]["post"]["requestBody"]["content"]["application/json"], options?: { body?: unknown; headers?: Record<string, string>; idempotencyKey?: string }): Promise<paths["/api/runs/{id}/fork"]["post"]["responses"][201]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}/fork"]["post"]["responses"][201]["content"]["application/json"] | null>("POST", `/api/runs/${encodeURIComponent(id)}/fork`, { body: body ?? options?.body, headers: this.withIdempotency(options?.headers, options?.idempotencyKey) });
  }

  async readRunJournal(id: string): Promise<unknown[] | null> {
    return this.requestNdjson("GET", `/api/runs/${encodeURIComponent(id)}/journal`);
  }

  async readRunMetrics(id: string): Promise<paths["/api/runs/{id}/metrics"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}/metrics"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/api/runs/${encodeURIComponent(id)}/metrics`);
  }

  async answerQuestion(id: string, qid: string, body: paths["/api/runs/{id}/questions/{qid}"]["put"]["requestBody"]["content"]["application/json"], options?: { body?: unknown; headers?: Record<string, string>; idempotencyKey?: string }): Promise<paths["/api/runs/{id}/questions/{qid}"]["put"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}/questions/{qid}"]["put"]["responses"][200]["content"]["application/json"] | null>("PUT", `/api/runs/${encodeURIComponent(id)}/questions/${encodeURIComponent(qid)}`, { body: body ?? options?.body, headers: this.withIdempotency(options?.headers, options?.idempotencyKey) });
  }

  async cancelRun(id: string, options?: { headers?: Record<string, string>; idempotencyKey?: string }): Promise<paths["/api/runs/{id}:cancel"]["post"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/api/runs/{id}:cancel"]["post"]["responses"][200]["content"]["application/json"] | null>("POST", `/api/runs/${encodeURIComponent(id)}:cancel`, { headers: this.withIdempotency(options?.headers, options?.idempotencyKey) });
  }

  async health(): Promise<paths["/healthz"]["get"]["responses"][200]["content"]["application/json"] | null> {
    return this.requestJson<paths["/healthz"]["get"]["responses"][200]["content"]["application/json"] | null>("GET", `/healthz`);
  }

  async metrics(): Promise<string | null> {
    return this.requestText("GET", `/metrics`);
  }
}

function parseSseFrame(frame: string): unknown | undefined {
  const data: string[] = [];
  for (const line of frame.split("\n")) {
    if (line.startsWith(":")) continue;
    if (line.startsWith("data:")) data.push(line.slice(5).replace(/^ /, ""));
  }
  if (data.length === 0) return undefined;
  const text = data.join("\n");
  if (!text) return undefined;
  return JSON.parse(text) as unknown;
}

function problemMessage(problem: unknown): string {
  if (problem && typeof problem === "object" && "detail" in problem) {
    const detail = (problem as { detail?: unknown }).detail;
    if (typeof detail === "string") return detail;
  }
  return "";
}
