[package]
name = "qcg-llm-steps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
async-trait.workspace = true
camino.workspace = true
qcg-contract = { path = "../qcg-contract" }
qcg-engine = { path = "../qcg-engine" }
qcg-llm = { path = "../qcg-llm" }
minijinja.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
