use super::openapi_types::{
    ApiHeader, ApiParameter, ApiResponse, ApiRoute, ParameterSchema, ResponseBody, ResponseSchema,
};

const ERR_INTERNAL: &[u16] = &[500];
const ERR_RESOURCE: &[u16] = &[400, 404, 500];
const ERR_INVALID: &[u16] = &[400, 500];
const ERR_MCP_MUTATION: &[u16] = &[400, 403];
const ERR_MCP_CALLBACK: &[u16] = &[400, 403, 500];
const ERR_START_RUN: &[u16] = &[400, 409, 413, 422, 500, 503];
const ERR_INTERACTION: &[u16] = &[400, 404, 409, 422, 500, 503];
const ERR_MUTATION: &[u16] = &[404, 409, 500];

const NO_HEADERS: &[ApiHeader] = &[];
const NO_QUERY_PARAMETERS: &[ApiParameter] = &[];
/// Pagination bounds for `GET /api/runs`, shared by the OpenAPI document and
/// the server handler so the documented and enforced ranges cannot diverge.
pub const RUN_LIST_LIMIT_MIN: usize = 1;
pub const RUN_LIST_LIMIT_MAX: usize = 200;
pub const RUN_LIST_LIMIT_DEFAULT: usize = 50;
const RUN_LIST_QUERY_PARAMETERS: &[ApiParameter] = &[
    ApiParameter {
        name: "limit",
        required: false,
        schema: ParameterSchema::Integer {
            minimum: Some(RUN_LIST_LIMIT_MIN as u64),
            maximum: Some(RUN_LIST_LIMIT_MAX as u64),
            default: Some(RUN_LIST_LIMIT_DEFAULT as u64),
        },
    },
    ApiParameter {
        name: "cursor",
        required: false,
        schema: ParameterSchema::String,
    },
    ApiParameter {
        name: "state",
        required: false,
        schema: ParameterSchema::Ref("RunStatus"),
    },
    ApiParameter {
        name: "generator_id",
        required: false,
        schema: ParameterSchema::String,
    },
    ApiParameter {
        name: "since",
        required: false,
        schema: ParameterSchema::DateTime,
    },
];
const OAUTH_CALLBACK_QUERY_PARAMETERS: &[ApiParameter] = &[
    ApiParameter {
        name: "code",
        required: false,
        schema: ParameterSchema::String,
    },
    ApiParameter {
        name: "state",
        required: true,
        schema: ParameterSchema::String,
    },
    ApiParameter {
        name: "iss",
        required: false,
        schema: ParameterSchema::String,
    },
    ApiParameter {
        name: "error",
        required: false,
        schema: ParameterSchema::String,
    },
];
const NO_ADDITIONAL_RESPONSES: &[ApiResponse] = &[];
const IDEMPOTENCY_HEADERS: &[ApiHeader] = &[ApiHeader {
    name: "Idempotency-Key",
    description: "Retries with the same key and request body return the original run.",
    required: false,
}];
const LAST_EVENT_ID_HEADERS: &[ApiHeader] = &[ApiHeader {
    name: "Last-Event-ID",
    description: "Resume the event stream after this event sequence number.",
    required: false,
}];
const LOCATION_HEADERS: &[ApiHeader] = &[ApiHeader {
    name: "Location",
    description: "URL of the newly created run.",
    required: true,
}];
const ETAG_HEADERS: &[ApiHeader] = &[ApiHeader {
    name: "ETag",
    description: "Weak validator for conditional GET requests.",
    required: true,
}];
const IF_NONE_MATCH_HEADERS: &[ApiHeader] = &[ApiHeader {
    name: "If-None-Match",
    description: "Return 304 when this validator matches the current representation.",
    required: false,
}];
const NOT_MODIFIED_RESPONSES: &[ApiResponse] = &[ApiResponse {
    status: 304,
    description: "Not modified",
    body: ResponseBody::Empty,
    headers: ETAG_HEADERS,
}];

pub const API_ROUTES: &[ApiRoute] = &[
    ApiRoute {
        method: "get",
        path: "/healthz",
        summary: "Health check",
        response: ApiResponse {
            status: 200,
            description: "Server is healthy",
            body: ResponseBody::Json(None),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERNAL,
    },
    ApiRoute {
        method: "get",
        path: "/metrics",
        summary: "Prometheus metrics",
        response: ApiResponse {
            status: 200,
            description: "Prometheus text exposition",
            body: ResponseBody::Text("text/plain; version=0.0.4"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERNAL,
    },
    ApiRoute {
        method: "get",
        path: "/api/openapi.json",
        summary: "OpenAPI document",
        response: ApiResponse {
            status: 200,
            description: "OpenAPI document",
            body: ResponseBody::Json(None),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERNAL,
    },
    ApiRoute {
        method: "get",
        path: "/api/generators",
        summary: "List generators",
        response: ApiResponse {
            status: 200,
            description: "Available generators",
            body: ResponseBody::Json(Some(ResponseSchema::ArrayRef("GeneratorSummary"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERNAL,
    },
    ApiRoute {
        method: "get",
        path: "/api/generators/{id}",
        summary: "Describe a generator",
        response: ApiResponse {
            status: 200,
            description: "Generator detail",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("GeneratorDetail"))),
            headers: ETAG_HEADERS,
        },
        additional_responses: NOT_MODIFIED_RESPONSES,
        request_schema: None,
        request_headers: IF_NONE_MATCH_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/generators/{id}/assets/{path}",
        summary: "Read a declared generator asset",
        response: ApiResponse {
            status: 200,
            description: "Generator asset bytes",
            body: ResponseBody::Binary("application/octet-stream"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/mcp/servers",
        summary: "List configured MCP servers and authorization status",
        response: ApiResponse {
            status: 200,
            description: "Configured MCP servers",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("McpServerList"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERNAL,
    },
    ApiRoute {
        method: "post",
        path: "/api/mcp/servers/{id}/authorization",
        summary: "Start MCP OAuth authorization",
        response: ApiResponse {
            status: 200,
            description: "Authorization URL",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("McpAuthorizationStart"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_MCP_MUTATION,
    },
    ApiRoute {
        method: "delete",
        path: "/api/mcp/servers/{id}/authorization",
        summary: "Clear stored MCP OAuth authorization",
        response: ApiResponse {
            status: 204,
            description: "Authorization cleared",
            body: ResponseBody::Empty,
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_MCP_MUTATION,
    },
    ApiRoute {
        method: "delete",
        path: "/api/mcp/servers/{id}/authorization/pending",
        summary: "Cancel a pending MCP OAuth authorization",
        response: ApiResponse {
            status: 204,
            description: "Pending authorization canceled",
            body: ResponseBody::Empty,
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_MCP_MUTATION,
    },
    ApiRoute {
        method: "get",
        path: "/api/mcp/oauth/callback",
        summary: "Complete an MCP OAuth authorization callback",
        response: ApiResponse {
            status: 200,
            description: "Authorization completed",
            body: ResponseBody::Text("text/html"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: OAUTH_CALLBACK_QUERY_PARAMETERS,
        errors: ERR_MCP_CALLBACK,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs",
        summary: "List runs",
        response: ApiResponse {
            status: 200,
            description: "Known runs",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunListResponse"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: RUN_LIST_QUERY_PARAMETERS,
        errors: ERR_INVALID,
    },
    ApiRoute {
        method: "post",
        path: "/api/runs",
        summary: "Start a run",
        response: ApiResponse {
            status: 201,
            description: "Started run",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: LOCATION_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: Some("StartRun"),
        request_headers: IDEMPOTENCY_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_START_RUN,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}",
        summary: "Run snapshot",
        response: ApiResponse {
            status: 200,
            description: "Run snapshot",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: ETAG_HEADERS,
        },
        additional_responses: NOT_MODIFIED_RESPONSES,
        request_schema: None,
        request_headers: IF_NONE_MATCH_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "post",
        path: "/api/runs/{id}/fork",
        summary: "Fork a run from a durable checkpoint",
        response: ApiResponse {
            status: 201,
            description: "Forked run",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: LOCATION_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: Some("ForkRun"),
        request_headers: IDEMPOTENCY_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_START_RUN,
    },
    ApiRoute {
        method: "put",
        path: "/api/runs/{id}/questions/{qid}",
        summary: "Answer a pending run question",
        response: ApiResponse {
            status: 200,
            description: "Updated run snapshot",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: Some("AnswerPayload"),
        request_headers: IDEMPOTENCY_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERACTION,
    },
    ApiRoute {
        method: "put",
        path: "/api/runs/{id}/confirmations/{cid}",
        summary: "Confirm or deny a pending side effect",
        response: ApiResponse {
            status: 200,
            description: "Updated run snapshot",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: Some("ConfirmDecision"),
        request_headers: IDEMPOTENCY_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_INTERACTION,
    },
    ApiRoute {
        method: "post",
        path: "/api/runs/{id}:cancel",
        summary: "Cancel a run",
        response: ApiResponse {
            status: 200,
            description: "Settled run snapshot",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunSnapshot"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: IDEMPOTENCY_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_MUTATION,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/events",
        summary: "Subscribe to run events",
        response: ApiResponse {
            status: 200,
            description: "Server-sent event stream",
            body: ResponseBody::Text("text/event-stream"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: LAST_EVENT_ID_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/artifacts",
        summary: "Run output manifest",
        response: ApiResponse {
            status: 200,
            description: "Output manifest",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("OutputManifest"))),
            headers: ETAG_HEADERS,
        },
        additional_responses: NOT_MODIFIED_RESPONSES,
        request_schema: None,
        request_headers: IF_NONE_MATCH_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/artifacts/{path}",
        summary: "Read an artifact",
        response: ApiResponse {
            status: 200,
            description: "Artifact bytes",
            body: ResponseBody::Binary("application/octet-stream"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "delete",
        path: "/api/runs/{id}",
        summary: "Delete a terminal run",
        response: ApiResponse {
            status: 204,
            description: "Run deleted",
            body: ResponseBody::Empty,
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_MUTATION,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/artifacts.zip",
        summary: "Download all artifacts as zip",
        response: ApiResponse {
            status: 200,
            description: "Artifact zip",
            body: ResponseBody::Binary("application/zip"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/bundle",
        summary: "Download a self-contained run bundle as zip",
        response: ApiResponse {
            status: 200,
            description: "Run bundle zip",
            body: ResponseBody::Binary("application/zip"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/journal",
        summary: "Read run journal",
        response: ApiResponse {
            status: 200,
            description: "Run journal JSONL",
            body: ResponseBody::Text("application/x-ndjson"),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
    ApiRoute {
        method: "get",
        path: "/api/runs/{id}/metrics",
        summary: "Read run cost metrics",
        response: ApiResponse {
            status: 200,
            description: "Run cost metrics with USD estimate",
            body: ResponseBody::Json(Some(ResponseSchema::Ref("RunCostMetrics"))),
            headers: NO_HEADERS,
        },
        additional_responses: NO_ADDITIONAL_RESPONSES,
        request_schema: None,
        request_headers: NO_HEADERS,
        query_parameters: NO_QUERY_PARAMETERS,
        errors: ERR_RESOURCE,
    },
];
